FROM ubuntu:18.04
MAINTAINER Yiyu Jia <yiyu.jia@gmail.com>
#  $ docker build . -t continuumio/miniconda:latest -t continuumio/miniconda:4.5.4 -t continuumio/miniconda2:latest -t continuumio/miniconda2:4.5.4
#  $ docker run --rm -it continuumio/miniconda2:latest /bin/bash
#  $ docker push continuumio/miniconda:latest
#  $ docker push continuumio/miniconda:4.5.4
#  $ docker push continuumio/miniconda2:latest
#  $ docker push continuumio/miniconda2:4.5.4

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

# system package
#RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
#    libglib2.0-0 libxext6 libsm6 libxrender1 \
RUN apt-get update --fix-missing && apt-get install -y wget \
    python python-dev python-pip build-essential swig git libpulse-dev libasound2-dev

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda2-4.5.4-Linux-x86_64.sh -O ~/miniconda.sh && \
   /bin/bash ~/miniconda.sh -b -p /opt/conda && \
   rm ~/miniconda.sh && \
   ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
   echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc

#RUN pip install pocketsphinx textract spacy pyyaml pdfminer.six pdfminer
ADD environment.yml /tmp/environment.yml
RUN conda env create -f /tmp/environment.yml
# Pull the environment name out of the environment.yml
RUN echo "conda activate $(head -1 /tmp/environment.yml | cut -d' ' -f2)" >> ~/.bashrc
#RUN echo "conda activate base" >> ~/.bashrc
ENV PATH /opt/conda/envs/$(head -1 /tmp/environment.yml | cut -d' ' -f2)/bin:$PATH

CMD [ "/bin/bash" ]
